[metadata]
name = "git-files"
description = "A channel to list the files currently tracked in the Git repository"
requirements = ["git", "bat"]

[source]
command = "git ls-files $(git rev-parse --show-toplevel)"

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
enter = "actions:cd"
shift-enter = "actions:edit"

[actions.cd]
description = "Jump to the file's directory"
command = "cd $(dirname '{}') && $SHELL"
mode = "execute"

[actions.edit]
description = "Open file in nvim"
command = "NVIM_APPNAME=nvim_windows nvim '{}'"
mode = "execute"
