[helpers]

[default]
depends = []

[default.files]
"nvim" = "~/.config/nvim"
"wezterm/wezterm.lua" = "~/.wezterm.lua"
"starship/starship.toml" = "~/.config/starship.toml"
"zellij/config.kdl" = "~/.config/zellij/config.kdl"
"devbox/devbox.json" = "~/.local/share/devbox/global/default/devbox.json"
"gh-dash/config.yml" = "~/.config/gh-dash/config.yml"

[al.files]
"atuin" = "~/.config/atuin"

[nvim.files]
"nvim" = "~/.config/nvim"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"

[default.variables]

[settings]
default_target_type = "automatic"
