alias j="jjui"
alias l="lla -s date -l"
alias gha="gh-dash"
alias wt="watchexec -d 500ms -r --bell -N"
alias reload="source $HOME/.zshrc"
alias vi="nvim"
alias v="nvim"
alias vim="nvim"
alias nw="NVIM_APPNAME=nvim_windows nvim"
alias c="clear"
